name: Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  build:
    name: Run tests and generate coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run tests
        run: |
          set -eu -o pipefail

          dotnet test \
            --logger trx \
            --logger "console;verbosity=detailed" \
            --settings "runsettings.xml" \
            --results-directory pr/tests-results
      - name: Save PR information
        run: |
          echo "PR_NUMBER=${{ github.event.number }}" >> ./pr/pr.env
          echo "PR_BASE_REF=${{ github.base_ref }}"   >> ./pr/pr.env
          echo "PR_HEAD_REF=${{ github.head_ref }}"   >> ./pr/pr.env
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/